# Generated by Django 4.2.23 on 2025-07-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0002_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
            ],
            options={
                'permissions': [('can_view', 'Can view document'), ('can_create', 'Can create document'), ('can_edit', 'Can edit document'), ('can_delete', 'Can delete document')],
            },
        ),
    ]
